server:
  port: ${PORT}
spring:
  profiles:
    active: local
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: 0
      timeout: 2000ms
  jpa:
    hibernate:
      ddl-auto: update   # create / update / validate / none
    show-sql: true
springdoc:
  group-configs:
    - group: all
      paths-to-match: /**
logging:
  level:
    root: INFO
    com.multi.ouigo: DEBUG
    org.springframework.security: DEBUG

    # JDBC ?? ?? ????? ???????
    jdbc:
      resultset: OFF
      audit: OFF
      connection: OFF

---
spring:
  config:
    activate:
      on-profile: local,test
  datasource:
    url: jdbc:log4jdbc:mysql://${DB_HOST}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: INFO
    com.multi.ouigo: DEBUG
    org.springframework.security: DEBUG

    # JDBC ?? ?? ????? ???????
    jdbc:
      resultset: OFF
      audit: OFF
      connection: OFF


